# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 76aac525d3635e2c37b6803d0486913588bf277b8d75fc77e2dc7a0619bbd782ffab1635969f37a2c75ae5782087a8cfa64751ffbb1d5cb7cac66f5bd569dd46

test:
  secret_key_base: f4a63913329972508d4a0ec21229c68f5a40e11e1af3610187aa47eed866a0205e833fcd01a8a3f02e8e7b7faf625676d3f1350bd723047ad4b2f5d8c38e1647

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
